version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    # close kafka from outside
    ports: []
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    restart: on-failure:1000
    mem_limit: 512m

  db:
    image: mysql:5.7
    # My SQL 5.7 don't work in mac OS. MySQL 8.0 consume too much memory
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - broker-kafka
  
  consumer:
    container_name: consumer
    networks:
      - broker-kafka
    depends_on:
      - db
      - kafka
    build:
      dockerfile: DockerfileConsumer

  auto_refresh:
    networks:
      - broker-kafka
    depends_on:
      - db
      - kafka
    build:
      dockerfile: DockerfileAutoRefresh

  producer:
    container_name: producer
    depends_on:
      - consumer
      - kafka
    ports:
      - "5000:5000"
    networks:
      - broker-kafka
    build:
      dockerfile: DockerfileProducer

networks:
  broker-kafka:
    driver: bridge

volumes:
  mysqldata: