"""double description length

Revision ID: 27cf9ea615a5
Revises: 7dc248ed6d49
Create Date: 2025-08-03 13:02:54.318029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cf9ea615a5'
down_revision: Union[str, None] = '7dc248ed6d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'description',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=6000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'description',
               existing_type=sa.String(length=6000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
