"""Added ptime table

Revision ID: 3a75066a5eeb
Revises: 8a67177ddb76
Create Date: 2025-04-20 15:29:43.275121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a75066a5eeb'
down_revision: Union[str, None] = '8a67177ddb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p_time_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('v_type', sa.String(length=100), nullable=False),
    sa.Column('ctry_code', sa.String(length=50), nullable=False),
    sa.Column('p_time', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('p_time_record')
    # ### end Alembic commands ###
