"""Added tele id to user

Revision ID: ae3257411847
Revises: fff9b81b6880
Create Date: 2025-04-22 23:49:38.943344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3257411847'
down_revision: Union[str, None] = 'fff9b81b6880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_user', sa.Column('tele_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_user', 'tele_id')
    # ### end Alembic commands ###
