"""add priority

Revision ID: e5d28e620c36
Revises: 27cf9ea615a5
Create Date: 2025-09-02 14:09:11.278173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d28e620c36'
down_revision: Union[str, None] = '27cf9ea615a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('todo', 'priority', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'priority')
    # ### end Alembic commands ###
