"""Added todo table

Revision ID: fff9b81b6880
Revises: 3a75066a5eeb
Create Date: 2025-04-21 08:33:44.101198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff9b81b6880'
down_revision: Union[str, None] = '3a75066a5eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('parent_task', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
